name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: Auroratide/recent-commits@v0.1.0-beta.2
        id: recent-commits
        with:
          github-token: ${{ github.token }}
          main-branch: main
          last-push-branch: last-push-to-main
      
      - name: Output
        run: echo "${{ steps.recent-commits.outputs.message }}"
